### ISSUE TITLE
Align social media icons 

### ISSUE THREAD

**Issue by aparnamittal** [HridoyHazard/BetterColor#29]
![image](https://user-images.githubusercontent.com/100208233/193611152-c80ca3cc-64e5-422b-b9f8-8eaae95a9761.png)

**Comment by aparnamittal** [comment]
@HridoyHazard  pls assign me this issue

**Comment by aparnamittal** [comment]
@HridoyHazard will this issue be counted under hacktoberfest?  please add the label of hacktoberfest inside the issue 
![image](https://user-images.githubusercontent.com/100208233/193671049-db0bee86-52ae-4c0f-8996-a060e7b2c056.png)

**Comment by HridoyHazard** [comment]
of course! check the repo already added label
