### ISSUE TITLE
Fix the pick color container

### ISSUE THREAD

**Issue by Bibhavshah** [HridoyHazard/BetterColor#35]
![image](https://user-images.githubusercontent.com/78656387/193644260-f90a2b3f-7ce9-4c6d-bf8d-45dea76b35c4.png)

The CSS for the pick color container is not written properly, so Please assign me this issue so that I can fix it.

**Comment by Gautam-Hegde** [comment]
Hey @Bibhavshah its working fine on local machine! what could be the issue👀?

**Comment by Bibhavshah** [comment]
It's working fine but the CSS is not as great, and I will improve the CSS
