### ISSUE TITLE
Revamp frontend with Material UI

### ISSUE THREAD

**Issue by yadomkar** [HridoyHazard/BetterColor#4]
Petition to revamp design and layout using MUI with following capabilities:

- Floating bottom bar to switch text and background color.
- Implement mobile responsiveness.
- Fixed top bar with custom BetterColor logo and github button.
- Ability to change text content.
- Ability to change fonts and font size.

I would like to work on this as part of Hacktoberfest.

**Comment by HridoyHazard** [comment]
Good Luck 
Try To Do Everything and once and create pr

**Comment by yadomkar** [comment]
Closing as UI has already been revamped through another issue.
