### ISSUE TITLE
[BUG] - Style of the bottoms and width of the app!

### ISSUE THREAD

**Issue by jsapuyesp** [HridoyHazard/BetterColor#43]
### Fix the Styles of the app

I'm looking the app and i see some 'bugs' of the styles:

![imagen](https://user-images.githubusercontent.com/47274649/193721541-1a96defa-77ad-490a-a896-3f63ab15a7dc.png)

So... i can fix the heigth of buttons and the width of the app if you want!

_**Please asign me this issue for the HacktoberFest**_

**Comment by HridoyHazard** [comment]
can you plz see the active page again and let me know if the layout is still same or not ??

**Comment by uday03meh** [comment]
Hi, If someone is working on this issue try removing the 
**{max-width:720px}** 
from public/assets/bootstrap/css/bootstrap.min.css
I want to but I'm unable to set up this project on my laptop.

![image](https://user-images.githubusercontent.com/59679281/193778729-77b44ec4-2f9c-40c1-8c3f-5a2325cecfe8.png)

**Comment by Nidhi1k** [comment]
hello I want to contribute but there is no html page

**Comment by sri-rishi** [comment]
@HridoyHazard  can you assign me this issue

**Comment by jsapuyesp** [comment]
The app works correctly! No need this issue...
