### ISSUE TITLE
Hey want to improve the designing of social media icons and also the padding between them 

### ISSUE THREAD

**Issue by Shobhnik13** [HridoyHazard/BetterColor#63]
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Arpit-mohankar** [comment]
can i work on this

**Comment by zugzwang03** [comment]
if no one is working on it, can I be assigned for it?

**Comment by zugzwang03** [comment]
@HridoyHazard
