### ISSUE TITLE
I would like to add preloader to website.

### ISSUE THREAD

**Issue by samipak458** [HridoyHazard/BetterColor#76]
**Describe the Feature you want to end**
Add preloader

**Expected behavior**
Make user experience better if website take more time loading till that pre-loader runs

**Screenshots (optional)**

**Additional context (optional )**

**Comment by aniketnegii** [comment]
Hello @samipak458  and @HridoyHazard, I would like to make a contribution to this issue.

**Comment by aniketnegii** [comment]
I have raised a pull request(#82 ) against this issue, please verify.
