### ISSUE TITLE
Improve overall UI design

### ISSUE THREAD

**Issue by RioCantre** [HridoyHazard/BetterColor#85]
**Describe the Feature you want to end**
- Add new feature that would enhance the overall UI design of the website
- Add new template and redesign the website
- Make it look modern

**Expected behavior**
- User friendly 
- Responsive

**Comment by HridoyHazard** [comment]
are you doing it ?

**Comment by RioCantre** [comment]
> are you doing it ?

 Yes, I am. Thanks for assigning me.
