### ISSUE TITLE
Fix - Size of the buttons (heigth)

### ISSUE THREAD

**Issue by jsapuyesp** [HridoyHazard/BetterColor#94]
**Describe the bug**
The heigth of the buttons in the app is not okay, i can't read the text inside them

**Screenshots (optional)**
_Desktop:_
![imagen](https://user-images.githubusercontent.com/47274649/196847395-ce052b33-7a59-422a-b5ef-7e85146f884c.png)

**Additional context (optional )**
In other screen size
_Mobile:_
![imagen](https://user-images.githubusercontent.com/47274649/196847473-a44c579a-fd97-4232-b76e-fc929e131666.png)

_Ipad:_
![imagen](https://user-images.githubusercontent.com/47274649/196847524-708e3e89-772b-4796-8ac5-f3ef3563fe78.png)

I can fix this issue, please assign it to me!

**Comment by Lakhaninawaz** [comment]
can i fix this issue, please assign me!

**Comment by deepaksuthar40128** [comment]
can you assign it to me?

**Comment by JhoanAlvear** [comment]
i can help , assigne to me

**Comment by HridoyHazard** [comment]
make a pr plz. the person who will make it soon will get the merge soon
